"""Duck-typed host that core/transcription.run_queue and save_files talk to.

WhisperGUI implements this structurally (no explicit inheritance). Tests use a
lightweight fake instead of Tkinter.
"""
from __future__ import annotations

from typing import Any, Callable, List, Optional, Protocol, Sequence


class TranscriptionHost(Protocol):
    """Methods/attributes used by run_queue / save_files / document processing."""

    queue: list
    cancel_requested: bool
    queue_ctrl: Any
    root: Any  # object with after(ms, fn)
    ai_jobs: Any

    def log(self, msg: str, tag: Optional[str] = None) -> Any: ...

    def begin_file_log(
        self, source: str, name: Optional[str] = None, current: Any = None, total: Any = None
    ) -> Any: ...

    def log_file_event(
        self, msg: str, tag: Optional[str] = None, file_id: Any = None, callback: Any = None
    ) -> Any: ...

    def log_file_segment(self, *args: Any, **kwargs: Any) -> Any: ...

    def end_file_log(self, status: str, error: Optional[str] = None, file_id: Any = None) -> Any: ...

    def add_file_output(
        self, role: str, path: str, label: Optional[str] = None, file_id: Any = None
    ) -> Any: ...

    def set_file_prompt_callback(self, file_id: Any, callback: Callable) -> Any: ...

    def set_file_source(self, file_id: Any, path: str) -> Any: ...

    def ask_save_mp3_confirm(self, filename: str) -> bool: ...

    def save_files(self, *args: Any, **kwargs: Any) -> Any: ...

    def resolve_output_path(self, path: str) -> str: ...

    def resolve_output_paths(self, paths: Sequence[str]) -> List[str]: ...

    def reset_ui(self) -> Any: ...

    def _resolve_output_dir(self, path: str, opts: Any = None) -> str: ...

    def _resolve_mp3_output_dir(self, path: str, opts: Any = None) -> str: ...

    def _processed_marker(self) -> str: ...

    def _set_progress_value(self, value: Any) -> Any: ...

    def _register_ai_job(self, txt_path: str, export_md_to_docx: Any = None, log_file_id: Any = None) -> Any: ...

    def _schedule_cursor_postprocess(self, *args: Any, **kwargs: Any) -> Any: ...

    def _export_markdown_to_docx(self, md_path: str, log_file_id: Any = None) -> Any: ...

    def _maybe_log_all_complete(self, send_txt_to_cursor: Any, will_continue: Any) -> Any: ...

    def _maybe_play_finish_sound(
        self, play_requested: Any, send_txt_to_cursor: Any, will_continue: Any
    ) -> Any: ...

    def _report_skipped_and_offer_remove(self, skipped_paths: list) -> Any: ...

    def _mark_done_by_path(self, path: str) -> Any: ...
